import {withBasePath} from "@/lib/paths"
import type {Metadata} from "next"
import Link from "next/link"
import {notFound} from "next/navigation"
import {Breadcrumbs,PageHero,SectionHeader} from "@/components/site/page-shell"
import {getMaster,getMasters,getRelatedLiterature,getRelatedMedia,getRelatedRepertoire,getRelatedTechniques,getRelatedTimeline,getStyleForPerson} from "@/lib/data"
type Props={readonly params:Promise<{id:string}>}
export function generateStaticParams(){return getMasters().map(p=>({id:p.id}))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const p=getMaster((await params).id);return {title:p?p.name+"｜名家索引":"找不到人物",description:p?.summary,alternates:{canonical:p?"/masters/"+p.id:"/masters"}}}
function sourceName(url:string){const host=new URL(url).hostname.replace(/^www\./,"");const known:Record<string,string>={"ccom.edu.cn":"中央音樂學院","shcmusic.edu.cn":"上海音樂學院","hkco.org":"香港中樂團","sccm.edu.cn":"四川音樂學院","zjvaa.edu.cn":"浙江藝術職業學院","music.cuhk.edu.cn":"香港中文大學（深圳）音樂學院","bard.edu":"Bard College","uscycs.org":"California Youth Chinese Symphony","ihchina.cn":"中國非物質文化遺產網"};return known[host]||host}
export default async function MasterPage({params}:Props){
 const person=getMaster((await params).id);if(!person)notFound();const p=person!
 const repertoire=getRelatedRepertoire(p.name),techniques=getRelatedTechniques(p.name),styles=getStyleForPerson(p),literature=getRelatedLiterature(p.name),media=getRelatedMedia(p.name),timeline=getRelatedTimeline(p.name)
 return <><Breadcrumbs items={[{label:"首頁",href:"/"},{label:"名家索引",href:"/masters"},{label:p.name}]}/><PageHero label="人物檔案" title={p.name} description={p.summary} image="culture"/>
 <section className="section-band bg-card/50"><div className="content-wrap grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><aside><h2 className="font-serif text-2xl font-bold text-primary">人物速覽</h2><dl className="mt-5 font-sans">{[["生卒年",p.birth_death],["地域",p.region],["身份",p.roles],["機構",p.institution],["風格",p.style]].filter(([,v])=>v).map(([label,value])=><div key={label} className="border-t py-4"><dt className="font-bold text-primary">{label}</dt><dd className="mt-2 leading-7 text-muted-foreground">{value}</dd></div>)}</dl></aside>
 <div><SectionHeader title="人物相關曲目"/><p className="font-sans leading-8 text-muted-foreground">以下索引把可對應的人物與曲目連在一起，並保留作品形式及整理、改編等版本說明。</p>{repertoire.length?<ul className="mt-6 divide-y border-y">{repertoire.map(w=><li key={w.id} className="py-4 font-sans"><Link className="text-link font-bold" href={"/repertoire/"+w.id}>{w.title}</Link><span className="mt-1 block text-sm leading-6 text-muted-foreground">{[w.creator,w.type,w.style].filter(Boolean).join(" · ")}</span></li>)}</ul>:p.works.length?<ul className="mt-6 flex flex-wrap gap-3 font-sans">{p.works.map(w=><li key={w}><Link className="text-link" href={"/search?q="+encodeURIComponent(w)}>{w}</Link></li>)}</ul>:null}
 </div></div></section>
 {(media.length||literature.length)?<section className="section-band border-t"><div className="content-wrap grid gap-12 md:grid-cols-2">{media.length?<div><SectionHeader title="錄音與影音"/><ul className="divide-y border-y font-sans">{media.map(item=><li key={item.id} className="py-4"><a className="text-link font-bold" href={item.source} target="_blank" rel="noreferrer">{item.title}</a><p className="mt-1 text-sm leading-6 text-muted-foreground">{[item.performer,item.work,item.type].filter(Boolean).join(" · ")}</p></li>)}</ul></div>:null}{literature.length?<div><SectionHeader title="書目與延伸閱讀"/><ul className="divide-y border-y font-sans">{literature.map(item=><li key={item.id} className="py-4"><a className="text-link font-bold" href={item.source} target="_blank" rel="noreferrer">{item.title}</a><p className="mt-1 text-sm leading-6 text-muted-foreground">{[item.author,item.type,item.topic].filter(Boolean).join(" · ")}</p></li>)}</ul></div>:null}</div></section>:null}
 {timeline.length?<section className="section-band bg-card/50"><div className="content-wrap"><SectionHeader title="相關年表"/><ol className="grid gap-4 md:grid-cols-2">{timeline.map((item,index)=><li key={item.year+item.event+index} className="border-l-2 border-accent/55 pl-4 font-sans"><p className="font-bold text-primary">{item.year}</p><p className="mt-1 leading-7 text-muted-foreground">{item.event}</p>{item.sources.length?<ul className="mt-2 space-y-1 text-sm">{item.sources.map(source=><li key={source.url}><a className="text-link" href={withBasePath(source.url)} target="_blank" rel="noreferrer">資料來源：{source.title}</a></li>)}</ul>:null}</li>)}</ol></div></section>:null}
 {(techniques.length||styles.length)?<section className="section-band"><div className="content-wrap grid gap-12 md:grid-cols-2">{techniques.length?<div><SectionHeader title="連到演奏技法"/><ul className="space-y-4 font-sans">{techniques.map(t=><li key={t.id}><Link className="text-link font-bold" href={"/techniques/"+t.id}>{t.name}</Link><p className="mt-2 leading-7 text-muted-foreground">{t.description}</p></li>)}</ul></div>:null}{styles.length?<div><SectionHeader title="風格與文化背景"/>{styles.map(s=><p key={s.name} className="mb-5 font-sans leading-8 text-muted-foreground"><strong className="text-primary">{s.name}：</strong>{s.features}</p>)}<Link className="text-link" href="/journal/north-south">閱讀流派與地域的關係</Link></div>:null}</div></section>:null}
 {p.sources.length?<section className="section-band border-t"><div className="content-wrap"><SectionHeader title="人物資料與延伸閱讀"/><ul className="space-y-4 font-sans">{p.sources.map((url,i)=><li key={url}><a className="text-link" href={withBasePath(url)} target="_blank" rel="noreferrer">{sourceName(url)} · 人物資料 {p.sources.filter(s=>new URL(s).hostname===new URL(url).hostname).length>1?"（"+(i+1)+"）":""}</a></li>)}</ul></div></section>:null}</>
}

